### ISSUE TITLE
About the loss  problem

### ISSUE THREAD

**Issue by lzcGitHub** [gengyanlei/ssgan#2]
Thanks for your code first but there are some problems for me to run it.
In main.py line 121 to line 123, you used Loss_label1, Loss_fake1, Loss_unlabel1 while you only imported Loss_label, Loss_fake, Loss_unlabel in the losses.py . Are  Loss_label1 and  Loss_label mean the same loss? If so, I met RuntimeError: CUDA error: device-side assert triggered while compute the loss. Have you met an error like this?

**Comment by gengyanlei** [comment]
@lzcGitHub 
Sorry, didn't notice your message. I have run the code before, but when copying, I may have copied the error. I used to run the code, there is no error, I check it again, check if there is an error.

**Comment by gengyanlei** [comment]
@lzcGitHub 
Hello, my code should be no problem, I have run it before, but the resulting image does not work well. The reason is that it is partially optimal.
In addition, your question should be that there is a problem with your tag data. Maybe the number of tags exceeds the total number of settings?

**Comment by lzcGitHub** [comment]
Thanks for your reply!
